name: Generate schema

on:
  schedule:
    - cron: '0 0 * * *' 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Generate schema
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --bin generate_schema --features schema-gen
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add schema
          git diff --staged --quiet || git commit -m "Update schema"
          git push
